### ISSUE TITLE
tickrate problem

### ISSUE THREAD

**Issue by maclarens** [lakwsh/l4dtoolz#11]
hello!
sv_maxrate not unlock more than 30k
sv_minrate not unlock more than 30k

SourceMod Version: 1.12.0.7139
Metamod:Source version 2.0.0-dev+1293
game left 4 dead2  2.2.3.9 9309

**Comment by lakwsh** [comment]
Hello, `sv_maxrate` and `sv_minrate` do not need to be modified; they will be automatically configured based on the `-tickrate` value.

**Comment by deprid** [comment]
Hello there, I've removed `sm_cvar sv_minrate sv_minrate` and `sm_cvar sv_minrate sv_maxrate`, but the console `status` command still shows me `30000`... the odd thing is that after using your fork the smoothness of the game now feels so much better than the other fork I was using. Before, I used [Releases · fbef0102/Tickrate-Enabler](https://github.com/fbef0102/Tickrate-Enabler/releases), console `status` command showed `60000`. Your fork gives me `30000` but the game smoothness is much better. 

This is my launch parameters: `D:\steamcmd\l4d2\srcds.exe -high -condebug -console -game left4dead2 +ip 0.0.0.0 -port 27016 +log on +map c1m2_streets +sv_lan 0 +exec server -tickrate 60 +sv_setmax 31`

This is in related cvar in the server.cfg: `exec server_rates.cfg`

Related cvars in the server_rates.cfg:
```
//sm_cvar sv_minrate 60000
//sm_cvar sv_maxrate 60000
sm_cvar sv_minupdaterate 60
sm_cvar sv_maxupdaterate 60
sm_cvar sv_mincmdrate 60
sm_cvar sv_maxcmdrate 60
//sm_cvar rate 60000
sm_cvar net_splitpacket_maxrate 60000
sm_cvar sv_client_min_interp_ratio -1
sm_cvar sv_client_max_interp_ratio 0 
sm_cvar fps_max 90
sm_cvar nb_update_frequency "0.048"
sm_cvar net_splitrate 2
sm_cvar sv_client_cmdrate_difference 0
sm_cvar sv_clockcorrection_msecs 25
//sm_cvar sv_multiplayer_maxtempentities 40
sm_cvar net_maxcleartime "0.001"
```
Can you guide me how to make it to show `60000` in the console `status` command?

**Comment by lakwsh** [comment]
The situation you encountered doesn’t seem to align with my expectations. I just performed an actual test, and when using the launch option -tickrate 100, the status command shows my client rate as 100000. When I modified the launch option to -tickrate 60, status shows my client rate as 60000. It seems that I haven’t encountered the issue you mentioned. I suggest using net_graph 4 to obtain the actual tickrate data.
As a side note, the sv_minrate and sv_maxrate ConVars are used to limit the client’s data rate, which may require adjustments in other versions. However, in this version, the data rate value has been modified at a deeper level, making it unaffected by these two ConVars, so changing them won’t have any effect on the client.

**Comment by deprid** [comment]
I've just found the culprit. Your l4dtoolz fork's tickrate enabler function is not working, at least in my case. As side note, I use two cvars differently than the old l4dtoolz: `sv_force_unreserved 0` (old value is 1), `sv_steam_bypass 1` (old value is none). 

I also have installed the recommended plugin a2s_fix along with it for Bypass SteamID Verification feature (the main reason I use your l4dtoolz is because my clients keep getting `No Steam logon` error, but somehow, now my clients get some `timed out` error more frequently, although the old l4dtoolz have the `timed out` error as well as `No Steam logon`).

I reinstalled the old tickrate_enabler and enabled both `sm_cvar sv_minrate 60000`, `sm_cvar sv_maxrate 60000` (because without them enabled, it will be `30000` too). And then combined with your l4dtoolz fork, boom, `status` console command showed `60000`. I finished about 5+ test and re-test to confirm the issue.

Meaning, without the outside tickrate_enabler, using ONLY your l4dtoolz fork, the value is always `30000`. To get `60000` value and to get rid of `No Steam logon`, I have to use both the old tickrate_enabler and your l4dtoolz fork. I even saw one of my client oddly got `10000 `value (using your l4dtoolz only)?! How did he even got such value since the server was set (unintendedly) `30000`. 

So I hope you could fix this issue so that I don't need to install the old tickrate_enabler to get `60000`.
