### ISSUE TITLE
RejectConnection: IP - #Valve_Reject_Server_Full

### ISSUE THREAD

**Issue by Nocxx8** [lakwsh/l4dtoolz#9]
Hello lakwsh, I use your extension and I get the message #Valve_Reject_Server_Full even though there are free slots on the server.
I have a 14vs14 configuration with superversus 14sur and 14inf and 1 spectator slot, but when the server is with 25/29 players, that "Server full" message appears with no possibility for another player to join, can you please fix it.
Already tried with:
seerver.cfg
- sm_cvar sv_setmax 29
- sv_setmax 29
- sm_cvar sv_maxplayers 29
- sv_maxplayers 29
- sm_cvar sv_force_unreserved 1
- sv_force_unreserved 1

I also put the launch parameter as it is in the github +sv_setmax 29
./srcds_run -game left4dead2 -console -port 27015 +map c1m2_streets -tickrate 100 +ip 0.0.0.0 +sv_setmax 29

I used previous versions of l4dtoolz and I never had that #Valve_Reject_Server_Full problem, it seems strange to me that it comes out even though there are free slots on the server. (example 24/29, 25/29, 26/29, 27/29).

**Comment by lakwsh** [comment]
Hello, I couldn't reproduce the issue you mentioned. In order to better pinpoint the problem, could you please provide more information and try the following steps?
1. When the issue occurs:
> Enter `maxplayers` in the server console and check the prompt message.
> Enter `sv_maxplayers` in the server console and check the return value.
> Enter `sv_setmax` in the server console and check the return value.
> Enter `status` in the server console and check the prompt message.
2. Try entering `sv_setmax 31` and `sv_maxplayers 31` in the server console while no one is connected, then try reproducing the issue again.
3. Enter `plugin_print` in the server console and check the returned information.
  
**Note: You don't need to add the `sm_cvar` prefix for these commands.**

**Comment by lakwsh** [comment]
It has been acknowledged that the issue occurs intermittently. As it cannot be reproduced 100% reliably at the moment, further investigation is still required. Thank you for your feedback.

**Comment by lakwsh** [comment]
After analysis, the issue arises from the situation where the sum of players and infected players exceeds the maximum number of clients when a player joins the server, causing the server to be unable to allocate a client for the new player. This problem is likely to exist in other versions as well, and there is no satisfactory solution currently available.
![image](https://github.com/lakwsh/l4dtoolz/assets/13025769/9dcea83b-a964-414c-a99d-ae2092daee49)
